spring.application.name=FilmRentalFrontend

# Frontend runs on port 8080
server.port=8081

# Backend API base URL
backend.api.base-url=http://localhost:8085

# Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Jackson: handle Java 8 date/time
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
